### PR TITLE
X11,WS,Show Desktop,scroll,overload,barrier placement

### PR DESCRIPTION
**Pull request by G-dH**
Tested on two monitors configuration with Ubuntu 20.04.2, X11/Wayland, hope I didn't overlooked another bug..
Added:
- Native Show desktop function, wmctrl part removed
- Scroll to activate
- Scroll to switch workspace
- Switch to workspace action, ws index adjustable - if higher than actual ws count, last not empty ws is activated

Fixed:
- X11 unclickable corners above active windows (workaround)
- Pressure barrier placement correction
- Prefs overload reduction

### CODE REVIEW

**Comment by G-dH** [comment]
Hi, it looks like I just missed something more under wayland, I'll try to fix it soon.

**Comment by janxyz** [comment]
Hi, that's alright. I will have a look at this at the weekend.

**Comment by G-dH** [comment]
There is no problem with one monitor, but when the second one is active all corners start to act weirdly, doesn't make sense to me - scroll over corners doesn't respond at all, corners above the top panel doesn't respond to click either, and even if the corner is set to click and hot corner signal shuld not be connected, it reacts on mouse pressure.. Just wayland, X11 session is OK.

**Comment by G-dH** [comment]
Login to wayland while 2 monitors are active == problem. Disable and reenable second monitor == problem solved. Gnome 3.36.4

**Comment by janxyz** [comment]
Hi, I haven't looked at all the things in detail but here are some remarks.

- I would like to keep the _showDesktop method with wmctrl. I know the dependency is not nice but I used this because I wanted it to be compatible with the native hide all windows function of Gnome. Maybe the new method can be used as a fallback if wmctrl is not installed.
- The scroll over main panel feature is out of scope for this extension because it has nothing to do with the corners.
- I think it would be better if the "Switch to workspace - Index" field is only visible if the "Switch to specific Workspace" action is choosen, similar to "Run command" maybe.
- If I set primary button of a corner to "Toggle Overview" and set pressure for the same corner to "Toggle Overview" and then set pressure to nothing I get the following error when pressing primary button on that corner:
```
Mär 07 13:29:50 foobar gnome-shell[2192]: Object St.BoxLayout (0x55d9c201caf0), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Mär 07 13:29:50 foobar gnome-shell[2192]: == Stack trace for context 0x55d9be6d9930 ==
Mär 07 13:29:50 foobar gnome-shell[2192]: #0   55d9c1ce5ff0 i   resource:///org/gnome/shell/ui/ripples.js:91 (2068f4a335b0 @ 107)
Mär 07 13:29:50 foobar gnome-shell[2192]: #1   55d9c1ce5f50 i   /home/abc/.local/share/gnome-shell/extensions/custom-hot-corners@janrunx.gmail.com/extension.js:322 (1626b6344448 @ 50)
Mär 07 13:29:50 foobar gnome-shell[2192]: #2   55d9c1ce5ec0 i   /home/abc/.local/share/gnome-shell/extensions/custom-hot-corners@janrunx.gmail.com/extension.js:405 (1626b63f5880 @ 47)
Mär 07 13:29:50 foobar gnome-shell[2192]: #3   55d9c1ce5e30 i   /home/abc/.local/share/gnome-shell/extensions/custom-hot-corners@janrunx.gmail.com/extension.js:399 (1626b63eb178 @ 121)
Mär 07 13:29:50 foobar gnome-shell[2192]: #4   55d9c1ce5d78 i   /home/abc/.local/share/gnome-shell/extensions/custom-hot-corners@janrunx.gmail.com/extension.js:360 (1626b636f718 @ 524)
Mär 07 13:29:50 foobar gnome-shell[2192]: #5   7ffc1a938160 b   self-hosted:1011 (1626b63d7538 @ 454)
Mär 07 13:29:50 foobar gnome-shell[2192]: JS ERROR: Error: Argument 'child' (type interface) may not be null
                                           playAnimation@resource:///org/gnome/shell/ui/ripples.js:91:21
                                           _rippleAnimation@/home/abc/.local/share/gnome-shell/extensions/custom-hot-corners@janrunx.gmail.com/extension.js:322:23
                                           _toggleOverview@/home/abc/.local/share/gnome-shell/extensions/custom-hot-corners@janrunx.gmail.com/extension.js:405:18
                                           _runAction@/home/abc/.local/share/gnome-shell/extensions/custom-hot-corners@janrunx.gmail.com/extension.js:399:18
                                           _onCornerClicked@/home/abc/.local/share/gnome-shell/extensions/custom-hot-corners@janrunx.gmail.com/extension.js:360:14
```
- Makefile.am is missing misc-settings-widget.ui and still contains the prefs-widget.ui file.
- We could add a authors or contributors file or section. The readme title is not the right place for recognitions.
- This pull request should be split into multiple pull requests. There are just too many different things changed here.

**Comment by G-dH** [comment]
Hi, thank you for the input. The last updates wasn't subject of the original pull request nor planed at the time. This branch is just my playground, screenshots are from working copy, nothing I want to push to your master right now. 
- wmctrl doesn't do what I want - keep my Conky visible.
- Scroll over main panel feature  - yes but... I do use it and I've added workspace switching functionality to this extension - just one more switch and one less extension for me. Not to mention double settings. This extension is about desktop navigation for me and this part of it.
- Switch to workspace - good point
- Corner update bug should be fixed already
- Makefile will be updated eventualy
- It's not about credits, it's about distinction of the working copy
- Yes I have changed all and have no idea how to split it

I am a git newbie and not a programmer so please be patient with me.

**Pull request closed without merging**
