### PR TITLE
workaround: GS3.36/X11 barrier placement

### PR DESCRIPTION
**Pull request by G-dH**
Stupid barriers.. :) I'm sorry for the last update, I fully understood the bug late. I hope that this is final workaround for this bug. I've tested it successfully on both X11 and Wayland session on Ubuntu 20.04.2 with 2 monitors. In common use case, max one barrier have to be moved from the edge of the screen where secondary monitor is attached, so situation when the pointer gets behind the barrier and miss the trigger shouldn't occur.

### CODE REVIEW

**Comment by G-dH** [comment]
"Max one barrier" - that should be: "max one of the barrier's axis"..

**Comment by janxyz** [comment]
Sorry for taking so long to answer. I think this can be solved better by reverting the changes made in 36d93f9476e448556f8d415a95d2f834c6dc1314, except for the - 1 when calculating the actor position. I create a new PR for this #30. Maybe you could take a look at it and check if this would also work or if I'm missing something.

**Comment by G-dH** [comment]
My approach is to do things right and workaround bugs, not the opposite way.. In this case, you will be probably successful on Wayland too, but in fact you will be placing those barriers out of the screen and your code doesn't make much sense on first sight. When I saw it first time, I was really confused how it is possible that it works :)

**Comment by janxyz** [comment]
I think the barriers are supposed to be placed out of the screen for blocking left to right movement. This is also how it's done in Gnome Shell. For example (without any hot corner extensions enabled) lets say you have a setup with two monitors side by side and each monitor has a resolution of 1920x1080 pixel.

```
+---------+---------+
|         |         |
|    A    |    B    |
|         |         |
+---------+---------+
```
If monitor A is the primary monitor Gnome Shell would put a barrier in the top right corner with the x position at 1920 [0]. If you use X11 and move the mouse pointer against the barrier the maximum x position you would get to is 1919. But if you use Wayland the maximum x position is actually 1920. So I think it's actually Waylands fault. You can check the mouse position with https://extensions.gnome.org/extension/1141/screen-coordinates/.

[0] https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/js/ui/layout.js#L528

**Comment by G-dH** [comment]
No, the barrier must behave the same way whether you set BarrierDirection positive or negative, it's nonsense to place anything off the screen (and for negative BarrierDirection only) to work inside the screen. And it causes those collisions, if it worked correctly you could place two barriers with opposite directions right next to each other without the need to move one by 1 pixel and make 1 px gap between them.

**Comment by janxyz** [comment]
> No, the barrier must behave the same way whether you set BarrierDirection positive or negative

They do behave the same way, but you still have to place right or bottom barrier at coordinates that are outside of the screen because the barrier is along the left or top side of the specified pixel. See 12.3 in https://cgit.freedesktop.org/xorg/proto/fixesproto/plain/fixesproto.txt

**Comment by G-dH** [comment]
Thanks for the link, now I see it... I didn't realize that the barriers came as a part of X server and therefore my attempts to find proper documentation weren't successful. Now it make sense since the design aim to something else than hot corners :D Thank you for your time!

**Pull request closed without merging**
