### PR TITLE
fixed: unclickable corners above active window; ...

### PR DESCRIPTION
**Pull request by G-dH**
Hi, today just quick fix for your last version.
Look at my current extended version and let me know what you think. I think that merge with your project is out of question now..

### CODE REVIEW

**Comment by G-dH** [comment]
I've finally fixed another bug of the original code, which sort of worked, but was causing problems on multi monitor configuration and Wayland.

**Comment by janxyz** [comment]
Hi, I really appreciate your work. Seems like I introduced that barrier position bug some time ago in 3a3ba3b0a8e7cc6689b1785e7ac4980cb66d68a5. The PR looks good. I will push a new version to https://extensions.gnome.org/ with the changes.

It looks like you invested quite some work into your extended version. Impressive! You should go ahead and publish your version to the extension website as well!

**Comment by G-dH** [comment]
Thanks, OK, I will publish my version soon. I've solved the issue with unstable monitors order too, if you are interested. At least in a way that Monitor 1 preferences are always applied to primary monitor.

**Comment by G-dH** [comment]
Now I found out why you calculated those corner coordinates like that.. Another stupid bug, related to X11 (Edit: actually to Wayland as I realized later). You have to place right and bottom barriers out of the screen, when you want them to work exactly at the edge (not one pixel inside) of the screen while hitting them. Damn, I have to fix it again...

**Pull request merged**
